unified workflow

diff --git a/.github/workflows/publish_and_render.yml b/.github/workflows/publish_and_render.yml
--- a/.github/workflows/publish_and_render.yml
+++ b/.github/workflows/publish_and_render.yml
@@ -3,7 +3,7 @@ on:
   push:
     branches: separate_documentation
 
-name: Render PDF
+name: Quarto Publish and Render PDF
 
 jobs:
   build-deploy:
@@ -19,7 +19,18 @@ jobs:
         with:
           tinytex: true  # Ensure LaTeX is installed for PDF rendering
 
-      - name: Render Specific Quarto Document to PDF
+      - name: Render Quarto Project
+        uses: quarto-dev/quarto-actions/render@v2
+        with:
+          path: docs  # Specify the path to your Quarto project
+
+      - name: List files for debugging
+        run: |
+          ls -la docs
+          ls -la docs/_site
+          ls -la
+
+      - name: Render Documentation Quarto Document to PDF
         uses: quarto-dev/quarto-actions/render@v2
         with:
           to: pdf
@@ -28,29 +39,23 @@ jobs:
       - name: Move PDF
         run: mv docs/_site/PANKEGG_documentation.pdf docs/PANKEGG_documentation.pdf
 
-      - name: List files for debugging
-        run: |
-          ls -la docs
-          ls -la docs/_site
-          ls -la 
-
       - name: Delete README.md
-        run: rm README.md
+        run: rm -f README.md || true  # Use `|| true` to prevent failure if README.md does not exist
 
-      - name: Render README to GFM
+      - name: Render GitHub README to GFM
         uses: quarto-dev/quarto-actions/render@v2
         with:
           to: gfm
           path: docs/README.qmd
-      
-      - name: List files for debugging
-        run: |
-          ls -la docs
-          ls -la docs/_site
-          ls -la 
 
       - name: Move README.md to root
         run: mv docs/README.md ./README.md
+
+      - name: remove Contributing.md
+        run: rm -f README.md || true 
+
+      - name: Move CONTRIBUTING.md to root
+        run: mv docs/CONTRIBUTING.md ./CONTRIBUTING.md
 
       - name: Commit PDF and README
         run: |
@@ -59,3 +64,11 @@ jobs:
           git add docs/PANKEGG_documentation.pdf README.md
           git commit -m "Rendered PDF and README from documentation"
           git push
+
+      - name: Publish to GitHub Pages
+        uses: quarto-dev/quarto-actions/publish@v2
+        with:
+          target: gh-pages
+          path: docs
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
